a = int(input())
for i in range(a):
    i = (input())
    j = (input())
    setx = set([a for a in i])
    sety = set([y for y in j])
    setz=frozenset('foobar')
    setz2=set('foobar')
    #print(setx.union(sety))
    # print(setz[2])
    print(setz2)
    # for i in range(len(setz)):
    #     print(setz.pop())
    # if setx.union(sety) == set():
    #     print("NO")
    # else:
    #     print("YES")